### PR TITLE
Role assignation fail

### PR DESCRIPTION
**Pull request by marc-aurele-besner**
## Role assignation fail

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Simplified the logic in `ChainProvider` by removing the cookie-based network setting and directly using `indexerSet.network`.
- Enhanced `queryGraphqlServer` to extract the network ID from the callback URL instead of relying on cookies, improving reliability and error handling.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ChainProvider.tsx</strong><dd><code>Simplify network selection logic in ChainProvider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/providers/ChainProvider.tsx

<li>Removed cookie setting logic for network selection.<br> <li> Simplified state management by directly using <code>indexerSet.network</code>.<br> <li> Removed unnecessary <code>network</code> state variable.<br>

</details>

  </td>
  <td><a href="https://github.com/autonomys/astral/pull/839/files#diff-a55a9b593552c3724c0ea05e726001ec210930c00c73a6549093b80abe4f7ced">+1/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>queryGraphqlServer.ts</strong><dd><code>Use callback URL for network ID extraction in GraphQL queries</code></dd></summary>
<hr>

explorer/src/utils/queryGraphqlServer.ts

<li>Replaced cookie-based network selection with callback URL parsing.<br> <li> Extracted network ID from callback URL for API selection.<br> <li> Improved error handling for missing callback URL or network ID.<br>

</details>

  </td>
  <td><a href="https://github.com/autonomys/astral/pull/839/files#diff-f40ff168b3c311be1e65bb57eba822755f4caea1666911cd6a8f892e603b9070">+9/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by EmilFattakhov** [comment]
Can't confirm the fix on preview @marc-aurele-besner, but should be okay to test in prod.

**Review by EmilFattakhov — COMMENTED** [review]
Can't confirm the fix on preview @marc-aurele-besner, but should be okay to test in prod.

**Comment by marc-aurele-besner** [comment]
> Can't confirm the fix on preview @marc-aurele-besner, but should be okay to test in prod.

Now it should work in the preview

**Comment by clostao** [comment]
I don't understand how you get the network from the callbackURL pathname. In the deploy preview the value I see is `https://dev-astral.netlify.app` whose pathname is empty so the default indexer is set. In which case this may differ?

**Review by clostao — APPROVED** [review]

**Pull request merged**
